do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
end;
$$;

create schema auth;

create table auth.users (
  id uuid primary key,
  email text
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  role text not null default 'user',
  status text not null default 'active'
);

create table public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null,
  action text not null,
  target_type text not null,
  target_id text,
  details text,
  created_at timestamptz not null default now()
);

grant usage on schema public to anon, authenticated, service_role;
grant usage on schema auth to service_role;
grant select on table public.profiles, public.admin_logs to service_role;
